# Site settings
title: Nikolay Redko
description: >- # this means to ignore newlines until "baseurl:"
  Software development services since 1995
baseurl: ""  # the subpath of your site, e.g. /blog
url: "http://www.nredko.com" # the base hostname & protocol for your site, e.g. http://example.com
repository: nredko/nredko.github.io


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name          : Nikolay Redko
  image         : assets/img/redko.jpg
#  behance       : nredko
# dribbble      : your_username
  email         : nredko@nredko.com
#  facebook      : nredko
  github        : nredko
# gitlab        : your_username
# instagram     : your_username
  linkedin      : nredko
#  medium        : your_username
  skype         : nredko?chat
# soundcloud    : your_username
# spotify       : your_username
# stackoverflow : your_user_id
  telegram      : nredko

# tumblr        : your_username.tumblr.com
# twitch        : your_username
# twitter       : your_username
# vimeo         : your_username
# youtube       : your_channel_name
# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock